name: Daily link check
on:
  schedule:
    - cron: 0 0 * * * # run daily
  workflow_dispatch: # run manually
    inputs: {}
jobs:
    check-links:
        name: runner / linkspector
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run linkspector
            uses: umbrelladocs/action-linkspector@v1
            with:
              github_token: ${{ secrets.github_token }}
              reporter: local
              filter_mode: nofilter
              config_file: '.linkspector.yml'
              fail_on_error: true
    